# Generated by Django 4.0.2 on 2022-03-21 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication_category',
            options={'verbose_name': 'Publication Category', 'verbose_name_plural': 'Publication Categories'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/person'),
        ),
    ]
