# Generated by Django 4.0.2 on 2022-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_category',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='pub_category/'),
        ),
    ]
