# Generated by Django 4.0.2 on 2022-03-21 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_publication_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 13, 39, 7, 692004)),
        ),
    ]
