# Generated by Django 4.0.2 on 2022-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_person_email_person_facebook_person_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
