# Generated by Django 4.0.2 on 2022-06-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_publication_category_background'),
        ('web', '0003_person_email_person_facebook_person_linkedin_and_more'),
    ]

    operations = [
    ]
