# Generated by Django 4.0.2 on 2022-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_publication_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='PIC',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
