# Generated by Django 4.0.2 on 2022-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_event_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='PIC',
            new_name='Person_In_Charge',
        ),
    ]
