# Generated by Django 4.0.2 on 2022-06-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_publication_image_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
