# Generated by Django 4.0.2 on 2022-06-21 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_event_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_credit',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
