# Generated by Django 4.0.2 on 2022-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_event_moderator_event_closing_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closing_remarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='ClosingSpeaker', to='web.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='opening_speech',
            field=models.ManyToManyField(blank=True, null=True, related_name='OpeningSpeaker', to='web.Person'),
        ),
    ]
