# Generated by Django 4.0.2 on 2022-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_publication_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
