# Generated by Django 4.0.2 on 2022-06-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_merge_20220620_1016'),
        ('web', '0008_alter_publication_image_credit'),
    ]

    operations = [
    ]
