# Generated by Django 4.0.2 on 2022-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
